[project]
name = "product-api"
version = "0.1.0"
description = "商品管理 API"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.111.0",
    "pydantic>=2.7.1",
    "uvicorn[standard]>=0.29.0",
] 